### ISSUE TITLE
can us for android studio?

### ISSUE THREAD

**Issue by hdev72** [Placeholder-Software/Dissonance-Demo#2]
Hello dear admin
Your project is really great, my question is, can it be used for Android Studio? or if not, Can you introduce me to a library like Dissonance that I can use in Android Studio?

**Comment by martindevans** [comment]
Dissonance is a plugin for the [Unity game engine](https://unity.com/) and so your application needs to be running inside Unity for you to be able to use Dissonance. So I guess that's probably not what you want?

I don't know much about Android development, so I can't make any other recommendations, sorry.
